postgresclusterNFSStaticPV:
  enabled: true
  storageClassName: efs-storage-class-efs-sc
  volumeHandle: fs-0b0e82f453eebc594

postgrescluster:
  enabled: true
  postgresVersion: 16
  postGISVersion: 3.4
  pgBouncerReplicas: 1
  monitoring: false
  supplementalGroups:
    - 26
  instances:
  - name: example
    replicas: 1
    dataVolumeClaimSpec:
      storageClassName: efs-storage-class-efs-sc
      volumeName: efs-pv-example
      accessModes:
      - "ReadWriteMany"
      resources:
        requests:
          storage: 300Mi
